import { Geist, Geist_Mono,Manrope,Playfair_Display,Poppins} from "next/font/google";
import "../../global.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const playfair = Playfair_Display({
  weight: ['500', '700'], // choose weights you need
  subsets: ['latin'],
  display: 'swap',
});
const manrope = Manrope({
  weight: '500',
  subsets: ['latin'],
});
const poppins = Poppins({
  weight: '500',
  subsets: ['latin'], // adjust if needed
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
